Avoid double-memory usage on numpy output type
Synerise/cleora pull request #50
Opened 2022-04-11 13:57 UTC by Ajk4

2022-04-12 06:24 UTC, kodieg requested changes

2022-04-12 06:24 UTC, kodieg commented on src/persistence.rs
> +            let mmap = Box::new(mmap);
Dodaj może do NpyWriteContext konstruktor new(mmap) i przenieś przygotowanie `mmap_ptr` i `mmap_data` tworzenie  `NpyWriteContext` tam.

2022-04-12 06:24 UTC, kodieg commented on src/persistence.rs
> +                .mmap_data
Dodaj do NpyPersistorContext funkcje ala:
```
fn data<'a>(&'a mut self) -> &'a mut ArrayViewMut<'a, ...>
```

Idealnei jakby się dało właśnie podmienić 'static z definicji typu na 'a, bo inaczej można próbować wyciągnać referencje do danych. 

Spróbuj zrobić z `NpyPersistorContetxt` bezpieczną abstrakcje.

2022-04-12 12:37 UTC, piobab approved these changes

2022-04-13 08:17 UTC, piobab commented
LGTM

2022-04-13 08:17 UTC, merged